# LorePowers by Aelithron

# Prefix
# This appears in front of all messages sent by the plugin.
# Supports color codes, guide: https://wiki.ess3.net/mc
Prefix: '&7[&dLorePowers&7]'

# Power Links
# This section allows linking powers to players.
PowerLinks:
  eb7ea62d-b7aa-4d6e-b68a-d7e948780f03: # This is Aelithron's UUID.
    - "VOID_TOTEMS" # Specify each of their powers.
